server:
  port: 38763

chessfactory:
  file: /media/mark/DATAPART1/lichess_db_standard_rated_2018-12.pgn.bz2
  readlimit: -1
  max-pgn-in-flight: 100000
  db-writer:
    batch-size: 200
    pool:
      corePoolSize: 8
      threadNamePrefix: db-writer-thread
  agg-calc:
    pool:
      corePoolSize: 32
      threadNamePrefix: agg-calc-thread

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management

spring:
  batch:
    job:
      enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: true
        jdbc:
          batch_size: 5
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chessfactory?user=chessfactory&password=chessfactory
    hikari:
      maximum-pool-size: 4