server:
  port: 38763

chessfactory:
  dir: /media/mark/DATAPART1/lichess12/
  files-regexp: .*.pgn.bz2
  readlimit: -1
  max-pgn-in-flight: 50000
  db-writer:
    batch-size: 10000
    pool:
      corePoolSize: 1
      maxPoolSize: 1
      threadNamePrefix: db-writer-thread
  agg-calc:
    pool:
      corePoolSize: 8
      maxPoolSize: 8
      queueCapacity: 0
      threadNamePrefix: agg-calc-thread

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management

spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    hikari:
      maximum-pool-size: 4
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver